"""Script that creates enumerations in definition format.

Usage: python generate_enum_definitions arg1 arg2
- arg1: file with enum members, one per line
- arg2: enum name

Output is written to stdout, and can be used as input for
definition parser
"""

import sys
from langtools.utils.accents import utf_to_proszeky

def main():
    enum_file_name = sys.argv[1]
    enum_name = sys.argv[2]
    enum_file = open(enum_file_name)
    enum_members = set([l.strip().decode("utf-8")
                        for l in enum_file.read().split("\n")])
    print "%File generated by machine/pymachine/scripts/generate_enum_definitions.py"
    for member in enum_members:
        print utf_to_proszeky(u"42 # N {0} # #: IS_A {1}".format(member,
            enum_name))

if __name__ == "__main__":
    main()
